### ISSUE TITLE
#pallet IBC OnRecvPacketAck is unclear return type

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/centauri#119]
# issue

https://github.com/CosmWasm/wasmd/blob/main/x/wasm/ibc.go#L236 on go they have Succh and Failed. There is no Nil.

Please document what is Nil and how to handle.

Also please document what is WriteFn, what is Any value and how to use it.

```rust
pub type WriteFn = dyn FnOnce(&mut dyn Any) -> Result<(), String>;

pub enum OnRecvPacketAck {
	Nil(Box<WriteFn>),
	Successful(Box<dyn Acknowledgement>, Box<WriteFn>),
	Failed(Box<dyn Acknowledgement>),
}
```

**Comment by dzmitry-lahoda** [comment]
Nil - I do not acknowledge.
Successful - any data from the contract.
Failed - high-level failure of the module ( we should use Transact in our module to revert)
WriteFn -  empty (ICS20 does something here). If @Wizdave97 will link us examples would awesome.

**Comment by Wizdave97** [comment]
Close in favour of https://github.com/ComposableFi/centauri/issues/134

The `OnRecvPacket` return type will be removed.
