### ISSUE TITLE
Signature verification efforts

### ISSUE THREAD

**Issue by blasrodri** [ComposableFi/centauri#123]
_This issue compiles the short-term journey for the R&D (math-focused) team._

- [ ] Study, give benchmarks and propose optimizations for https://github.com/privacy-scaling-explorations/halo2wrong/blob/master/ecdsa/ (please confirm if this is the one we are checking out)

In particular:
1. Give pen + paper understanding of the _topology_ of the circuit: number of constraints + on-chain costs (call data + proving times?)
2. Assess room for improvement
3. Compare to alternative implementation/frameworks (gnark/circom?)

**Comment by blasrodri** [comment]
@seunlanlege please feel free to update this

**Comment by seunlanlege** [comment]
I already said this on the sync call but our best option remains halo2. 

There are benchmarks that show halo2 has faster proving/verification times than circom.

I also said that the EF is at the forefront of zero knowledge research. 

Here's a PR to gnark adding support for ECDSA showing that they're using the EF's research https://github.com/ConsenSys/gnark/pull/372
