### ISSUE TITLE
implement create connection for cosmos chains

### ISSUE THREAD

**Issue by oshorefueled** [ComposableFi/centauri#125]
To add `create connections` for cosmos chains the following need to be satisfied. 

- [ ] implement `ibc_events` method
- [ ] implement `finality_notifications` method
- [ ] implement `query_client_state`
- [ ] implement `query_latest_ibc_events` method
- [ ] estimate_weight: return 0 from estimate weight so that tx `submit` is immediately processed for cosmos. 

Part of this work was already started on #103, implementations from the PR will be reused.

**Comment by akc2267** [comment]
Hey @oshorefueled, now that https://github.com/ComposableFi/centauri/pull/136 is merged, is this ticket complete?

**Comment by oshorefueled** [comment]
yes it is.
