### ISSUE TITLE
#pallet `on_chan_open_init` to provide weight  limit and allow to return used gas

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/centauri#129]
# Issue

`on_chan_open_init` signature does not provide gas limit nor allow to return back used gas.

`on_chan_open_init` invokes Cosmwasm VM, which needs a gas limit and returns the gas used value.

# Actual

IBC does not provide a way to negotiate prices. Expected that the sender of the IBC message will tell his price, and it will be provided as a weight to a module.

# Expected

`on_chan_open_init` to provide gas limit as Weight. And return value to allow return gas used.

**Comment by dzmitry-lahoda** [comment]
discussed - will settle later.

**Comment by Wizdave97** [comment]
Hardcode gas limits.

**Comment by dzmitry-lahoda** [comment]
Hardcode where? In pallet-cosmwasm?

**Comment by akc2267** [comment]
@dzmitry-lahoda the gas limit hardcoding needs to be done in pallet-cosmwasm. substrate doesn't have gas limits, so this is only applicable on the cosmwasm side. As for a sensible real limit, I'm guessing `--gas 50000000000` is a sensible limit, judging from this stackexchange thread: https://substrate.stackexchange.com/questions/3992/i-get-a-the-executed-contract-exhausted-its-gas-limit-when-attempting-to-inst

**Comment by dzmitry-lahoda** [comment]
For me `gas limit hardcoding needs to be done in pallet-cosmwasm. substrate doesn't have gas limits` is nonsense. @hussein-aitlahcen @aeryz please advice.

**Comment by vmarkushin** [comment]
@dzmitry-lahoda 
> on_chan_open_init invokes Cosmwasm VM, which needs a gas limit and returns the gas used value
Can you point to the code where the VM is invoked?

Also, substrate's weight != cosmwasm's gas, so I don't know if it's possible to convert between each other. In substrate weight is usually calculated using additional functions like [here](https://github.com/ComposableFi/composable/blob/4b6b816633a55a405c4a702ef796b349538dacab/code/parachain/frame/democracy/src/weights.rs#L89), so I guess if you want to estimate weight for you message you should use something like that.

**Comment by dzmitry-lahoda** [comment]
https://github.com/ComposableFi/composable/blob/4b6b816633a55a405c4a702ef796b349538dacab/code/parachain/frame/cosmwasm/src/ibc.rs#L333

**Comment by dzmitry-lahoda** [comment]
Ok, we will be fine with weight.

**Comment by dzmitry-lahoda** [comment]
any value then nothing is good

**Comment by blasrodri** [comment]
Can we close this?

**Comment by dzmitry-lahoda** [comment]
ibc callbacks should provide weight limit.

**Comment by dzmitry-lahoda** [comment]
i do not see other options.

**Comment by blasrodri** [comment]
MAX is OK for all?

**Comment by dzmitry-lahoda** [comment]
With gas.

1. there is always limit of gas on any contract platform which is like part of total gas in unit of time. why? imagine infinite loop in contact which will take all the time if MAX passed....
2. as per ibc whitepaper , either ibc relayer works with extrinsics consumer models provide (pallet-coswasm) or there is abstraction. as I see centauri chosen abstraction. so pallet-comswams do not have direct access to origin, package metadata and weight  of call.
3. Go IBC module host provide gas limit to cosmwasm in Cosmos ecosystem. Just FYI

I know how to do pallet-cosmwasm if it could registers its extnsics as callable by relayer or if pallet-ibc would provide gas limit in trait callback . I do not know how to handle without these option. 

Separate task should be done to provide research on how to handle things better. 

Imho the research could end up to be part of cosmwasm spec modification about comswams assumption of gas limit provided by hosts.
