### ISSUE TITLE
#pallet ibc Order enum is not up to spec 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/centauri#130]
# issue

1. IBC pallet provides None order which is not up to IBC spec
2. Also it lacks spec out variant
3. Cosmwasm IBC has no None

```rust
fn map_order(order: Order) -> IbcOrder {
	match order {
		Order::None => 
unimplemented!("bridge: team what we should do with it? it is neither by spec nor cosmwasm knows this (Order::OrderedAllowTimeout  is in spec)"),
		Order::Unordered => IbcOrder::Unordered,
		Order::Ordered => IbcOrder::Ordered,
					    }
}
```

# expected

either remove None or document expected handling (so always return error is weird)

**Comment by dzmitry-lahoda** [comment]
will be dropped

**Comment by Wizdave97** [comment]
Close in favour of https://github.com/ComposableFi/centauri/issues/134
