### ISSUE TITLE
cannot use centauri in reproducible builds

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/centauri#140]
# root cause

- pure rust https://github.com/rust-lang/cargo/issues/11192
- same for nix https://github.com/ipetkov/crane/issues/113

# solution

do not use workspace deps until bugs fixed

# alternative 

- be part of monorepo
- fix and release rust :) 

# not alternative

stop doing reproducible builds

**Comment by dzmitry-lahoda** [comment]
cc @obsessed-cake

**Comment by blasrodri** [comment]
Will fix it. Thanks @dzmitry-lahoda
