### ISSUE TITLE
improve process of client codegen for subxt

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/centauri#160]
# current:
1. wasm is built
2. node is built
3. node runs wasm
4. tcp call is done to get metadata from node
5. cp of code from subxt produced client

bad because process is many step, large built, needs opening ports, hard to put into nix.

# proposed
1. wasm is built
2. get metadata https://github.com/chevdor/subwasm from wasm blob
3. run subxt to get rs code

good because easy to build, no need to open ports, can easy swap wasm to point to any chain (so can build rs for any target pair of chains - rs per connection), runs well in nix, no copy pasted custom code, code works with any chain (will not fail depending of if chain wss or HTTP to get wasm)

**Comment by Wizdave97** [comment]
Working on this.
