### ISSUE TITLE
Make `account_id_to_ss58` infallible

### ISSUE THREAD

**Issue by aeryz** [ComposableFi/centauri#171]
Our [pallet-cosmwasm](https://github.com/ComposableFi/composable/tree/main/code/parachain/frame/cosmwasm) depends on account to string conversion to be infallible. Because the underlying VM has an `Into<String>` bound.
We want to use `ibc_primitives::runtime_interface::account_id_to_ss58` method but it seems like although the function internally is infallible, it returns a `Result` which is a deal breaker for us. Can we make it return `Vec<u8>` instead?

**Comment by blasrodri** [comment]
This is fixed right @aeryz
