### ISSUE TITLE
BEEFY: Validation against two authority sets

### ISSUE THREAD

**Issue by blasrodri** [ComposableFi/centauri#182]
Looking at:

https://github.com/ComposableFi/centauri/blob/b2dfef9bee0d0c7205f20b568a789726d406957d/algorithms/beefy/verifier/src/lib.rs#L58

We are checking that the number signatures should be higher than any of the thresholds defined by the current or the next validator set. Shouldn't we change this to only verify against the current validator set?

**Comment by Wizdave97** [comment]
The check is valid because if the authority set has changed in that block, then the new authorities would be the one to sign that justification.

**Comment by Wizdave97** [comment]
WE want to exist early if the number of signatures does not meet the minimum threshold for either the current set or the next set

**Comment by blasrodri** [comment]
Thanks
