### ISSUE TITLE
Add Flat Fee 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/centauri#253]
### **Why** 
We are only charging a fixed 0.4% fee now for transfers and that’s a very low dollar value for low value tokens. Hence we should implement a flat fee of $10 for certain whitelisted assets to boost our revenue stream. 

### **What** 
Non-flat fee asset - 0.4% 
Flat fee asset - $10 

 **Where we charge**
Same as 0.4% fee, on destination of KSM/DOT bridge

**$10 for flat fee assets**
The following list of assets will be considered flat fee assets. These are assets Composable is comfortable with holding on its balance sheet. Generally, flat fee assets will fall into the category of a chain’s native tokens and we will be charging $10/ bridging transaction: 

| Ecosystem   | Flat Fee Assets |
| ------------- | ------------- |
| DOT  | DOT |
| Kusama  | KSM,PICA,USDT  |

The collected fee will be sent to the multisigs on Picasso or Composable chain. 

_For reference:
We aren’t swapping collecting fee as a rush of transfers can impact Pablo’s pool balance_

**Flat fee Asset Pricing**
Flat fee’s definition = whether there is a pool on Pablo with that asset

For flat fee assets where we collect $10 of the token as fee, we will be querying Pablo’s spot price for the rate. 
This also means that a prerequisite of flat fee assets is that they need to have pools on Pablo (created + seeded), which can be added via governance proposals only. 

**New pools on Pablo**
List of new Pablo pools: 
| Polkadot Assets   | $Liquidity |
| ------------- | ------------- |
| DOT/KSM  | $10,000/pool |
| DOT/PICA  | $10,000/pool |
| DOT/USDT  | $10,000/pool |

**Comment by itsbobbyzz** [comment]
@kkast wallet to collect fees  https://composablefinance.slack.com/archives/D04DGE104AK/p1681818044954089
