### ISSUE TITLE
Scale encoding of ibc events for internal dashboard

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/centauri#254]
**Why** 
We need to track the usage of the bridge, and this can be done by scaling encoding of ibc events

**What** 
Set up scale encoding of ibc events + create internal dashboard on:
1. total number of transfers that the bridge has processed. success or fail
2. volume (in $) transferred on the bridge each way. KSM>DOT, DOT>KSM
3. asset type transferred. e.g KSM, PICA, DOT, USDT 
4. Source and destination

**Comment by dzmitry-lahoda** [comment]
i will not be able to deliver $ now. until we have defined final oracle to use. pablo pool, coinbase what ever. can do next time. as soon as pools will be good, can use it. hope we will handle $ in next tickets.

**Comment by dzmitry-lahoda** [comment]
ported to semantics of grafana and metrics https://github.com/ComposableFi/composable/blob/dz/74/submetrics/data-and-formulas.md

**Comment by josietyleung** [comment]
handled by gloria
