### ISSUE TITLE
Monitoring of funds for the two relayer accounts 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/centauri#282]
**Why** 
We currently have no means to know if the relayer accounts are out of funds 

**How** 
Set up monitoring in place for the two relayer accounts: 
64MrSHbjnbPACh3C7oUGHBvoyjdgnYEB8BRtTw9kptjgFTwx (LAYR)
5wcgm3bbotHBcSjpgN6uGV338XhxDGuB22BETxsbgaMwqhzT (PICA) 

Once it drops below a certain threshold (configurable), then we should receive a Slack notification

**Comment by dzmitry-lahoda** [comment]
ported to grafana metrics semantics https://github.com/ComposableFi/composable/blob/dz/74/submetrics/data-and-formulas.md

**Comment by dzmitry-lahoda** [comment]
snipped take literally and requirements taken literally will not work.

**Comment by josietyleung** [comment]
@bostercf can we do 1M for LAYR and 150K for PICA thanks

**Comment by dzmitry-lahoda** [comment]
![image](https://github.com/ComposableFi/centauri/assets/757125/6a04bb1d-0aef-4046-b46b-80f3f977a22f)

**Comment by dzmitry-lahoda** [comment]
![Uploading Screenshot_20230511_104356_Nova.jpg…]()

**Comment by dzmitry-lahoda** [comment]
![Screenshot_20230511_104356_Nova](https://github.com/ComposableFi/centauri/assets/757125/a82d7899-e71d-4e8a-9837-27344d7f9704)
![Screenshot_20230511_104322_Nova](https://github.com/ComposableFi/centauri/assets/757125/251058f2-a320-4b88-9c99-87d0f0ce8c74)

**Comment by dzmitry-lahoda** [comment]
There 10M tokens of LAYR. It spends 100 per  deliver. if deliver each 4 blocks (whic hit is not, sure more), block 12 second.

>>> (((10000000/100)*4)*12)/60/60/24
55.55555555555555 days to spend 10M

So solving this concrete task is low prio because it does not solves all other tasks and solving others task needs more robust approach (either light client or bigquery indexer) than simple RPC calls (it will not work and be super brittle).

https://web.telegram.org/a/#-819788250

So we will have exact solution soon.

From PM perspective only this task should not be done and solved, until it solves all other monitoring tasks.

**Comment by dzmitry-lahoda** [comment]
More, from ended amounts nothing bad happens. In 5 minutes they will tell us on discord. So we could wait longer for general solution.

**Comment by dzmitry-lahoda** [comment]
I already know what will happen. 2 month will happen. No alert from SRE service. Why? Service was down. Discord people will alert us. We will top up.

**Comment by dzmitry-lahoda** [comment]
But given that we are less than 4 blocks, more like 10 blocks, it will take longer to fail.

**Comment by dzmitry-lahoda** [comment]
@bostercf would be awesome you align your work with me and @faboweb to avoid waste of cycles imho.

**Comment by blasrodri** [comment]
Closing this, based on what has been outlined here:
https://composablefinance.slack.com/archives/C02MSA16DCP/p1683807785091309

**Comment by dzmitry-lahoda** [comment]
I had this thing running. But work was stopped and indexing stuff is under FE team. 
Deployment of monitor was not finalized.
