### ISSUE TITLE
Multihop tx on mainnet (backend only, no fe)

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/centauri#302]
**Why**
With the existing implementation, if a user wants to send DOT from Polkadot Relay Chain to a DOT pool on Osmosis, she will need to perform the following steps: 

1. XCM DOT from Polkadot > Composable 
2. IBC DOT from Composable > Picasso, charges $10 flat fee 
3. IBC DOT from Picasso > Banksy, charges $10 flat fee 
4. IBC DOT from Banksy > Osmosis, 

So that’s 4 transactions that the user will have to sign and she will have to pay $20. 

**How**
We will need to develop a batching solution, so user can select any source + destination chain they want and: 

1. Only have to sign 1 transaction 
2. Only have to pay $10 fee once 
3. This batching/ multihop will need to work for any XCM + IBC combination e.g XCM > IBC > XCM. Or IBC > XCM > IBC etc 

**Solution** 
TBC. One option previously discussed was memo field, it's also what Osmosis is using to perform multi hop swaps

**Comment by blasrodri** [comment]
Is this a Centauri task, or should we develop also that's XCM aware as well?

**Comment by blasrodri** [comment]
Also, suggestion is to follow this standard as close as possible to avoid re-inventing the wheel

https://github.com/strangelove-ventures/packet-forward-middleware

**Comment by itsbobbyzz** [comment]
Added section on error handling in the [Cosmos Chain + Centuari strategy](https://docs.google.com/document/d/1-rXTTnhiSn1vqV3yKBtA4fYMv9zSiqbJXBIIsk4v9HY/edit
<img width="1203" alt="Screenshot 2023-06-09 at 12 17 40" src="https://github.com/ComposableFi/centauri/assets/88450750/5e8c68d9-6967-4f9b-b444-c549491df5e3">
#) doc for consideration.

**Comment by dzmitry-lahoda** [comment]
transfers do not fail

**Comment by josietyleung** [comment]
hi @RustNinja @itsbobbyzz @kollegian another thing to do prior to launching batching tx is that we'll want to add all the assets we support on the FE to the BYOG options on composable + picasso as well. 

This is to cater for: 
1. If user is transferring GLMR from moonbeam to osmosis. So moonbeam > composable > picasso > centauri > osmosis 
2. And the tx from composable > picasso fails 
3. Then the GLMR stays on composable 
4. And the user will need to initiate a new tx from composable > osmosis to retry 
5. Then user will need to set gas fee option as the default for composable is LAYR

**Comment by josietyleung** [comment]
closing as done
