### ISSUE TITLE
Validate if the asset is registered on the asset registry prior to tx 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/centauri#306]
**Why** 
We can currently send any token through the bridge. It eventually fails after ~20 blocks. 
This isn't great UX as assets that aren't allowed on the bridge shouldn't be relayed 
See slack thread: https://composablefinance.slack.com/archives/C03KZSFAD2Q/p1681898348281559

**How** 
Add in a validation so the tx fails immediately, with an error message explaining the reason

**Comment by dzmitry-lahoda** [comment]
it is not bridge issue. it fixed on fe and partially with permisionless assets in composable.
