### ISSUE TITLE
Optimize the performance/execution time for integration tests

### ISSUE THREAD

**Issue by RustNinja** [ComposableFi/centauri#321]
- here is the entry point of integration tests: `parachain_to_parachain_ibc_messaging_full_integration_test`
the execution time takes a lot of time. it affect each pr that created for centauri.
There are few potential places where optimisation will reduce the time execution.

**Comment by josietyleung** [comment]
pending mainnet

**Comment by RustNinja** [comment]
related and closed by this solution:
https://github.com/ComposableFi/centauri/issues/331
https://github.com/ComposableFi/centauri/pull/329
