### ISSUE TITLE
Hyperspace build hang up

### ISSUE THREAD

**Issue by AlejoLovallo** [ComposableFi/centauri#401]
Running ```cargo build -p hyperspace``` or ```cargo build -p hyperspace --release``` the process hang out during building of subtxt-generated inside hyperspace-parachain. 

<img width="1118" alt="Screenshot 2023-09-06 at 10 27 15" src="https://github.com/ComposableFi/centauri/assets/49210713/d44982cd-825d-4b7f-8a7e-7823af50a1da">

**Comment by blasrodri** [comment]
What machine are you using to generate this? You can also use the latest hyperspace built on docker hub as well.
https://hub.docker.com/r/composablefi/composable-centauri
