### ISSUE TITLE
Benchmark and research batch signature verification in solidity

### ISSUE THREAD

**Issue by pepebndc** [ComposableFi/centauri#58]
Research validity and benchmark performance of batch ECDSA and ECDSA* signature verification in solidity.

So, what I think it could be beneficial for the bridging strategy, in incremental order of complexity/time to production/scalability benefit:
- 1: A heuristic to analyze same signer/same message strategy.
	If the validator set remains constant during the epoch, we can precompute some of the signature verification. The same applies if we are verifying the same message (block).
	We can take some common factor and optimize signature verification.
- 2: Apply the batching algorithm presented in the paper. Using ECDSA*, we can get up to 30-40% more efficient.
- 3: Employ ZK to send proof of the validity of the signatures.
	The idea is to use a recursive recursive ZK proofs to proof the validity of all signatures in a given block. As in all recursive relationships there is a base and general case.
  	- Base case: You proof the first signature.
  	- General case: You have a circuit to prove the t signature and the t-1 proof.
  	At the end you have a single proof that verifies all the previous T signatures. This is expensive for the prover and the process it's sequential, but I think it can be all done off-chain. We can have relayers became provers.
  	
based on the slack message: https://composablefinance.slack.com/archives/C0418RW2UH2/p1664554688135079

**Comment by nadeemb53** [comment]
# Benchmarks

Repo link: https://github.com/ComposableFi/sol-ecdsa-benchmarks

### NoCacheEcrecover

> Contract for benchmarking ecrecover precompile using foundry's forge tests, looping through `n` number of signatures. An event is emitted with the number of correct matches.

### EcdsaOps

> Contract includes looping through each signature and recovering each address from the message hash and signature using `ECDSA.recover` function. Finally, an event is emitted with the number of correct matches.

### Openzeppelin ECDSA recover (signature verification)

| Number of signatures verified | Gas Usage | Gas Price (Eth) (15 Gwei) | USD (at 1500/eth) |
|-------------------------------|-----------|---------------------------|-------------------|
| 1                             | 30381     | 0.0004                    | 0.6               |
| 20                            | 152751    | 0.0022                    | 3.3               |
| 2000                          | 13143370  | 0.1971                    | 295.65            |
| 4000                          | 26653668  | 0.3998                    | 599.7             |
| 4340                          | 28989246  | 0.4348                    | 652.2             |

### ecrecover precompile

| Number of signatures verified | Gas Usage | Gas Price (Eth)(15 Gwei) | USD (at 1500/eth) |
|-------------------------------|-----------|--------------------------|-------------------|
| 1                             | 11276     | 0.00016                  | 0.24              |
| 20                            | 78721     | 0.00118                  | 1.77              |
| 2000                          | 7119578   | 0.10679                  | 160.18            |
| 4000                          | 14247110  | 0.21370                  | 320.55            |
| 8000                          | 28548929  | 0.42823                  | 642.385           |
| 8405                          | 29996915  | 0.44995                  | 674.925           |

**Comment by seunlanlege** [comment]
safe to close this now that the question has been answered
