### ISSUE TITLE
Adding Cosmos Support to hyperspace

### ISSUE THREAD

**Issue by oshorefueled** [ComposableFi/centauri#93]
To add a new chain to hyperspace, the chain needs to implement the Chain, *IbcProvider, Keyprovider, Send and Sync traits.* Each implemented method would then be registered in `hyperspace/core/src/chain` by calling them from their respective AnyChain method  in the hyperspace core crate. (Maybe this can be refactored?)

[https://github.com/ComposableFi/centauri/blob/master/hyperspace/core/src/chain.rs#L122](https://github.com/ComposableFi/centauri/blob/master/hyperspace/core/src/chain.rs#L122)

**Possible Refactoring of the AnyChain Implementation:**

Currently Chain, IbcProvider and KeyProvider traits are implemented on the AnyChain enum with the goal of supported chains being defined as variants on the enum. Each supported chain then has to call its equivalent methods from the AnyChain methods in a match case. [https://github.com/ComposableFi/centauri/blob/master/hyperspace/core/src/chain.rs#L126-L151](https://github.com/ComposableFi/centauri/blob/master/hyperspace/core/src/chain.rs#L126-L151)
This would lead to more code to maintain in match cases as more chains are support is added.   

My suggestion is to return the Chain trait from the `into_client` method rather than returning the AnyChain enum type. I think @vmarkushin called it dynamic dispatching in rust. Using that removes the need to register every implemented method by every supported chain in that file. 

**IbcProvider Trait**

The required query methods that need to be implemented to implement the IbcProvider trait can be found here [https://github.com/ComposableFi/centauri/blob/master/hyperspace/primitives/src/lib.rs#L83](https://github.com/ComposableFi/centauri/blob/master/hyperspace/primitives/src/lib.rs#L83)

Some of the methods in the IbcProvider might not translate directly to a cosmos chain. Meaning they might either not be needed to process cosmos messages or the requirement of the method might not be possible in cosmos. Some of these uncertain methods are. 

- `channel_whitelist`
- `expected_block_time`
- `query_client_update_time_and_height`
- `connection_prefix`
- `client_id`
- `connection_id`
- `client_type`
- `query_timestamp_at`
- `query_client_id_from_tx_hash`
- `is_update_required`

**KeyProvider Trait** 

The required query methods that need to be implemented to implement the KeyProvider trait can be found here [https://github.com/ComposableFi/centauri/blob/master/hyperspace/primitives/src/lib.rs#L337](https://github.com/ComposableFi/centauri/blob/master/hyperspace/primitives/src/lib.rs#L337)

**Chain Config**

A Cosmos chain config needs to be defined as struct such that chain configuration can be defined in a configuration file and parsed into the `CosmosChainConfig` struct. The defined config can then be used to initialize an hyperspace `Cosmos Chain Client`. A sample of how a `Substrate Chain Client` is initalized for a config here. [https://github.com/ComposableFi/centauri/blob/master/hyperspace/core/src/chain.rs#L614-L621](https://github.com/ComposableFi/centauri/blob/master/hyperspace/core/src/chain.rs#L614-L621)

**Comment by seunlanlege** [comment]
> My suggestion is to return the Chain trait from the into_client method rather than returning the AnyChain enum type. I think @vmarkushin called it dynamic dispatching in rust. Using that removes the need to register every implemented method by every supported chain in that file.

yes dynamic dispatch is preferrable at this level.

**Comment by seunlanlege** [comment]
> Some of the methods in the IbcProvider might not translate directly to a cosmos chain. Meaning they might either not be needed to process cosmos messages or the requirement of the method might not be possible in cosmos. Some of these uncertain methods are.

Any method that isn't async should be gotten from config

**Comment by Farhad-Shabani** [comment]
Some of the steps you mentioned here have already been accomplished under the MVP project we defined in Informal (Cosmos<>Cosmos through Hyperspace) to move toward generic design for Cosmos<>Parachain and lay the foundation for addressing light clients' concerns.
This [fork](https://github.com/Farhad-Shabani/centauri/commits/farhad/cosmos-cosmos) can be turned into a PR. 
The code is based on the `seun/integration-test` branch and working more on it can close issue #94

Steps taken so far:
- Create Cosmos related packages in accordance with `ComposableFi/centauri` repository
- Scaffold required traits, structs and functions
- Define `CosmosClientConfig` struct
- Define `CosmosClient` struct
- Connect clients to local chains and check some status through RPC endpoints
- Implement `KeyProvider` trait for `CosmosClient`
- Implement some methods of `IbcProvider` trait `CosmosClient` **(WIP)**

Blockers so far:
- There are some methods that accept or return Substrate-specific types, like
`IbcProvider` trait -> methods:`query_client_id_from_tx_hash` & `initialize_client_state`
`Chain` trait -> method: `submit`

**Comment by seunlanlege** [comment]
> There are some methods that accept or return Substrate-specific types, like
IbcProvider trait -> methods:query_client_id_from_tx_hash & initialize_client_state
Chain trait -> method: submit

So none of these methods are actually substrate specific:

> `query_client_id_from_tx_hash`

You should query for a `client_id` emitted by a `MsgCreateClient` tx using the tx hash and a block hash,

> `initialize_client_state`

You should construct the initial `ClientState` & `ConsensusState` needed to initialize a client.

> `Chain::submit`

You should encode the given ibc txs in your chain's tx format and submit when ensuring they are successfully executed on chain and return the associated block hash and tx hash or return an error.

I would assume that cosmos using 256 bits for it's block hash and tx hash types, alternatively we can make it an associated type if that's not the case to make it agnostic

**Comment by oshorefueled** [comment]
Did a quick overview of your fork, definitely a good place to start. And yeah, looks like implementing the  `query_client_id_from_tx_hash`, `initialize_client_state` and `submit` should close #94, so definitely speeds things up. You can  create a PR and we can start from there. 

> Some of the steps you mentioned here have already been accomplished under the MVP project we defined in Informal (Cosmos<>Cosmos through Hyperspace) to move toward generic design for Cosmos<>Parachain and lay the foundation for addressing light clients' concerns. This [fork](https://github.com/Farhad-Shabani/centauri/commits/farhad/cosmos-cosmos) can be turned into a PR. The code is based on the `seun/integration-test` branch and working more on it can close issue #94
